package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserPassowrdDO;

public interface UserPassowrdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Jun 13 15:48:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Jun 13 15:48:56 CST 2019
     */
    int insert(UserPassowrdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Jun 13 15:48:56 CST 2019
     */
    int insertSelective(UserPassowrdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Jun 13 15:48:56 CST 2019
     */
    UserPassowrdDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Jun 13 15:48:56 CST 2019
     */
    int updateByPrimaryKeySelective(UserPassowrdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Jun 13 15:48:56 CST 2019
     */
    int updateByPrimaryKey(UserPassowrdDO record);

    UserPassowrdDO selectByUserId(Integer userId);
}